import type { ImgHTMLAttributes } from 'react';

type Props = Omit<ImgHTMLAttributes<HTMLImageElement>, 'src'> & {
  src: string;
  alt: string;
};

const RE = /\.(jpe?g|png)$/i;

/**
 * `<picture>` wrapper that prefers the WebP twin generated by
 * `pnpm images`. Falls back to the JPG/PNG for browsers without
 * WebP support (rare in 2026).
 *
 * Caller still passes the JPG path — we derive the .webp twin by
 * replacing the extension, matching the pipeline output layout.
 */
export function ResponsiveImage({ src, alt, ...rest }: Props) {
  if (!RE.test(src)) {
    // Already a webp/svg/etc — render plain <img>
    return <img src={src} alt={alt} {...rest} />;
  }
  const webp = src.replace(RE, '.webp');
  return (
    <picture>
      <source srcSet={webp} type="image/webp" />
      <img src={src} alt={alt} {...rest} />
    </picture>
  );
}
